import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gothaPro = localFont({
  src: [
    {
      path: "../font/GothaProReg.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/GothaProMed.otf",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-gotha-pro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothaPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
